services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=players
    
  player_application:
    image: playerapp:latest
    ports:
      - 8080:8080
    environment:
      - PLAYERS_FILE=players.csv
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=players
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres